In [1]:
# Introduction to Numpy
# The NumPy liabrary is the core library for scientific computing in Python. 
# It provides a high - performance multi-dimensional array object, and tools for working with these arrays.

# Use the following import convention to import numpy

import numpy as np

In [2]:
#  np.zeros  creates array of Zeros
#  np.ones   creates array of Ones 

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.zeros((1,2))

array([[0., 0.]])

In [5]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [6]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.zeros((10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [12]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
np.zeros((10,10,10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [16]:
# Create an array of evenly spaced values (step value)

# within the braces, it indicates(start, stop, step value)

d = np.arange(10,25,5)
print(d)

[10 15 20]


In [18]:
d = np.arange(2,53,5)
print(d)

[ 2  7 12 17 22 27 32 37 42 47 52]


In [22]:
# Create an array of evenly spaced values 9number of samples)

d = np.linspace(0,2,9)
d

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
d = np.linspace(0,20,3)
d

array([ 0., 10., 20.])

In [24]:
d = np.linspace(0,25,4)
d

array([ 0.        ,  8.33333333, 16.66666667, 25.        ])

In [25]:
# Create a constant array

a = np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

In [30]:
a = np.full((5,5),9)
a

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [31]:
a = np.full((5,4),9)
a

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [32]:
a = np.full((2,5),9)
a

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [34]:
# create a 2*2 identity matrix

f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [35]:
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
f = np.eye(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
f = np.eye(10)
f

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
# Create an array with random values

np.random.random ((2,2))

array([[0.43707528, 0.1983565 ],
       [0.11490664, 0.08928004]])

In [39]:
np.random.random ((2))

array([0.50907305, 0.50237417])

In [40]:
np.random.random ((2,3,4))

array([[[0.10172124, 0.17529697, 0.37256282, 0.30626813],
        [0.61996253, 0.38588085, 0.18770727, 0.83294643],
        [0.12399446, 0.81981081, 0.87699818, 0.34583515]],

       [[0.40950556, 0.84652587, 0.44021521, 0.2439954 ],
        [0.65013178, 0.29019704, 0.50478989, 0.28250666],
        [0.75440675, 0.18229416, 0.95913876, 0.51483471]]])

In [41]:
np.random.random ((2,3))

array([[0.89705137, 0.65446379, 0.43629506],
       [0.56547111, 0.22369122, 0.51533286]])

In [42]:
np.random.random ((1,2,3))

array([[[0.84962343, 0.73688378, 0.15512607],
        [0.13007825, 0.64100724, 0.08719881]]])

In [43]:
np.random.random ((4,5,6))

array([[[0.97365984, 0.73897495, 0.59282765, 0.95758063, 0.54764366,
         0.17970556],
        [0.78682054, 0.33188162, 0.93410627, 0.04665074, 0.23005406,
         0.10188102],
        [0.68525343, 0.77189827, 0.65222956, 0.54193426, 0.54684796,
         0.7149868 ],
        [0.1325668 , 0.7281949 , 0.19848451, 0.53671219, 0.67828883,
         0.51167254],
        [0.88875728, 0.24550798, 0.29765913, 0.21997476, 0.52784071,
         0.24697026]],

       [[0.39071093, 0.73285281, 0.2508865 , 0.30515204, 0.40122836,
         0.30217908],
        [0.17094199, 0.01398995, 0.18002207, 0.50138861, 0.59233224,
         0.31105618],
        [0.25199935, 0.59499293, 0.68067412, 0.91145972, 0.4348223 ,
         0.00168788],
        [0.46634034, 0.46940138, 0.87953981, 0.91636044, 0.71076244,
         0.50194915],
        [0.85050618, 0.83944187, 0.51426287, 0.48480901, 0.61910323,
         0.94366682]],

       [[0.21971823, 0.42266568, 0.98406291, 0.5570791 , 0.07784231,
         0.864469

In [44]:
# Create an empty array

np.empty((2,3))

array([[0.84962343, 0.73688378, 0.15512607],
       [0.13007825, 0.64100724, 0.08719881]])

In [45]:
np.empty((3,2))

array([[0.84962343, 0.73688378],
       [0.15512607, 0.13007825],
       [0.64100724, 0.08719881]])

In [49]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [50]:
type(my_list)

list

In [55]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [56]:
arr1 = np.array(my_list)
arr1

array([1, 2, 3])

In [57]:
type(arr1)

numpy.ndarray

In [66]:
mat = [[1,2],[3,4],[5,6]]
mat

[[1, 2], [3, 4], [5, 6]]

In [68]:
mat = np.array(mat)
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
type(mat)

numpy.ndarray

In [65]:
arr = np.array(mat)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
mat.shape

(3, 2)

In [71]:
arr.shape

(3, 2)

In [72]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
mylist = [1,2,3,4,5,6]
mylist

[1, 2, 3, 4, 5, 6]

In [74]:
arr = np.array(mylist)
arr

array([1, 2, 3, 4, 5, 6])

In [75]:
arr

array([1, 2, 3, 4, 5, 6])

In [76]:
# shape function is used to know the resolution of an array

arr.shape

(6,)

In [77]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
arr.ndim                                                # This is a 1 dimensional array

1

In [79]:
mat.ndim                                                # This is a 2 dimensional array  

2

In [80]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [82]:
np.arange(10,12,3)

array([10])

In [83]:
np.arange(-2,2,8)

array([-2])

In [84]:
np.arange(5,2,1)

array([], dtype=int32)

In [86]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
np.zeros((3,3)).ndim

2

In [92]:
np.random.random((2,2,2,2)).ndim

4

In [99]:
my_arr = np.arange(0,11)                                 # It will return an array from 0 to 10
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
# Access one element from an array by calling out their indeces

my_arr[1]                                               # It will return element at index 10

1

In [101]:
my_arr[5]                                         

5

In [103]:
my_arr[10] 

10

In [107]:
# Access more than one element from an array

my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
my_arr[1:5]                          # It will return all the elements between 1 and 5 excluding 5

array([0, 1, 2, 3, 4])

In [110]:
my_arr[0:5]                          # It will return all the elements between 0 and 5 excluding 5

array([0, 1, 2, 3, 4])

In [111]:
my_arr[:5]                           # It will return all the elements between 0 and 5 excluding 5

array([0, 1, 2, 3, 4])

In [112]:
my_arr[8:]                            # It will return all elements from index 8 and beyond

array([ 8,  9, 10])

In [113]:
my_arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
my_arr[-2:]

array([ 9, 10])

In [115]:
my_arr[:-3]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [125]:
arr_2d = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [135]:
arr_2d = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [137]:
arr_2d[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [144]:
arr_2d[0:2,1:]

array([[1, 2],
       [4, 5]])

In [147]:
arr_2d[1:2,2:]

array([[5]])

In [157]:
arr_2d[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [148]:
arr_ad = np.array([[0,1,2,3,4],[3,4,5,6,7],[6,7,8,9,0],[9,10,11,12,13]])
arr_ad

array([[ 0,  1,  2,  3,  4],
       [ 3,  4,  5,  6,  7],
       [ 6,  7,  8,  9,  0],
       [ 9, 10, 11, 12, 13]])

In [152]:
arr_ad[1:1,3:1]

array([], shape=(0, 0), dtype=int32)

In [153]:
arr_ad = np.array([[0,1,2,3,4],[3,4,5,6,7],[6,7,8,9,0],[9,10,11,12,13]])
arr_ad

array([[ 0,  1,  2,  3,  4],
       [ 3,  4,  5,  6,  7],
       [ 6,  7,  8,  9,  0],
       [ 9, 10, 11, 12, 13]])

In [158]:
arr_ad[2:,2:]

array([[ 8,  9,  0],
       [11, 12, 13]])

In [163]:
arr_ad[0:2]

array([[0, 1, 2, 3, 4],
       [3, 4, 5, 6, 7]])

In [164]:
arr_ad[0:1]

array([[0, 1, 2, 3, 4]])